name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC 12 & Artifacts
            CC: gcc-12
            CXX: g++-12
            artifacts: true
          - name: Clang 13 & ODR
            CC: clang-13
            CXX: clang++-13
            use-odr: true

    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      ODR_TEST: ${{matrix.odr-test == true}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure stuff
        run: |
          sudo apt install nasm g++-12
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DODR_TEST=$ODR_TEST -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/tmp ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Install
        if: ${{matrix.artifacts == true}}
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --target install
          cd ../tmp
          install -D ../LICENSE share/doc/revil-toolset/LICENSE.md
          install -D ../toolset/README.md share/doc/revil-toolset/README.md

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Upload Artifacts
        if: ${{matrix.artifacts == true}}
        uses: actions/upload-artifact@v2
        with:
          name: RevilToolset-linux-amd64
          path: ${{github.workspace}}/tmp
          retention-days: 5

  build-widle:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure stuff
        run: |
          choco install ninja
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..
        env:
          CC: clang
          CXX: clang++
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Install
        run: |
          cmake --build build --target install
          copy LICENSE bin/LICENSE.md
          copy toolset/README.md bin/README.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RevilToolset-win64
          path: ${{github.workspace}}/bin
          retention-days: 5
